### ISSUE TITLE
NestTableの編集リンク、参照ダイアログ上で動かない

### ISSUE THREAD

**Issue by yoshiharuyasuda** [ISID/iPLAss#100]
参照ダイアログに表示しているNestTableの編集リンクをクリックしても、参照ダイアログが表示されない。
行追加時に編集リンクにイベントを追加する際に、ダイアログ上での利用の考慮がもれていた。

**Comment by xkazama-yukio3** [comment]
ダイアログは表示されるようになったが、以下のエラーがある。

①ダイアログ表示→ダイアログで保存→NestTableから再度ダイアログ表示
⇒ ダイアログが表示されない。(editReferenceでも同様の対応が必要か)

②ダイアログ表示→キャンセル
⇒「入力が保存されていませんがよろしいですか？」の確認が２回表示される。
⇒その後、「エラーが発生しました」と表示される。

**Comment by xkazama-yukio3** [comment]
対応完了。
