### ISSUE TITLE
gem、バージョン管理されているEntityのCSVダウンロード時に検索条件の「すべてのバージョン」フラグを考慮する

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#1000]
gem、バージョン管理されているEntityのCSVダウンロード時に検索条件の「すべてのバージョン」フラグを考慮するようにする。
現状はバージョン管理されているEntityの場合無条件で全部のバージョンがダウンロード対象になっている。

**Comment by yoshiharuyasuda** [comment]
_(English)_
Consider the "all versions" flag in the search conditions when downloading the CSV of gems and version-controlled entities.
Currently, in the case of version-controlled Entities, all versions are unconditionally subject to download.
