### ISSUE TITLE
gem、編集画面の自動補完でうまく補完されないパターンがある（ReferencePropertyEditor以外）

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#1035]
gem、編集画面の自動補完でうまく補完されないパターンがある。

- Radio形式、Checkbox形式の場合、同じ値を返すと、値が反転してしまう
- Select形式の場合、 `boolean` 値や `null` 値を返すと値が設定されない
- 多重度が複数の場合に、補完値として値をクリアする方針が曖昧 (※1)

ReferencePropertyEditorや検索条件の補完処理については別Issueで対応する。

※1 補完値のクリア方針を以下とする。
- 返却値が `null` の場合、先頭の値をクリアする（現行の動作を踏襲、現状は先頭のみクリア）
- 返却値が `[]` （空配列）の場合、全件をクリアする
- 返却値が配列の場合、それぞれの位置に値を設定。`null` が指定されているものは値をクリアする
　(a)返却値の数 < 画面表示行数 の場合、返却値より多い行はクリアする
　(b)返却値の数 > 画面表示行数 の場合、返却値の分、行を追加して表示する。
　　ただし、多重度を最大値として制御する。

**Comment by xkazama-yukio3** [comment]
_(English)_
In gem, there is a pattern in the auto completion process on the edit screen that does not complete correctly.

- In the case of Radio and Checkbox type, if the same value is returned, the value is inverted.
- In case of Select type, if `boolean` or `null` value is returned, the value is not set.
- When multiplicity is multiple, the policy of clearing values as complementary values is ambiguous (*1)

ReferencePropertyEditor and the completion process for search conditions will be addressed in another Issue.

(*1) The policy for clearing completion values is as follows.
- If the returned value is `null` , the first value is cleared (following the current behavior, currently only the first value is cleared).
- If the returned value is `[]` (an empty array), clear all the positions.
- If the returned value is an array, set a value at each position; if `null` is specified, clear the value.
　(a) If number of returned values < number of rows displayed on the screen, the rows with more returned values are cleared.
　(b) If number of returned values > number of rows displayed on the screen, additional rows are displayed for the returned values. However, the multiplicity is controlled as the maximum value.
