### ISSUE TITLE
日付系PropertyEditor、Datepickerの設定項目の追加（minDate、maxDate、テキストフィールドをreadOnlyに）

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#1041]
日付系PropertyEditor、Datepickerに次の設定項目を追加する。
- minDate
- maxDate
- テキストフィールドのreadOnly可否（直接入力の制限）
- minDate, maxDate は、設定によってファンクション実行可能とする
 
UI対応
- Datepicker にクリアボタンを追加する。

**Comment by xsekiguchi** [comment]
_(English)_

Add the following configuration items to the date-based PropertyEditor and Datepicker.

- minDate
- maxDate
- Text field readOnly (restriction of direct input)
- minDate and maxDate can be set to execute functions.

UI support

- Add a clear button to Datepicker.
