### ISSUE TITLE
BulkUpdateのjavadoc改善

### ISSUE THREAD

**Issue by xsuzukiyosuke** [ISID/iPLAss#1046]
BulkUpdateのjavadoc改善。
BulkUpdateの場合のバージョン管理時はバージョン番号を明示的に指定必要なことをどこかに注意書きしておく。

**Comment by HiguchiKiyoshi** [comment]
_(English)_
Improve javadoc for BulkUpdate.
Note that the version number must be explicitly specified when managing the version of BulkUpdate.
