### ISSUE TITLE
EQLをCLIで実行できるようにする

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#105]
EQLをCLIで実行できるようにするバッチ・シェルを提供する。

EQLの実行計画を取得したい場合（本番環境などで）、
EQL->SQLのマッピングは実際にEQL発行しログ出力しないとわからないが、

- EQL発行はadminConsoleにログインしないとできない。
- EQL（SQL）ログは設定を有効化しないとできない＆関係ないログも出力されてしまう。

ため、本番環境で取得するのはちょっとはばかれる。
なので、本番環境（のAPサーバ）とは関係ないプロセスで実行できるようにする。

**Comment by xwada** [comment]
対応完了。
