### ISSUE TITLE
参照セクションでネストプロパティのプロパティ名が選択できない

### ISSUE THREAD

**Issue by yoshiharuyasuda** [ISID/iPLAss#111]
参照セクションでネストプロパティ指定時、プロパティ名のプルダウンを展開してもうまく読み込めず、選択が出来ない。
プロパティ名をコピペで貼り付ければ設定は出来るが、フォーカスアウト時にワーニングのメッセージが表示される。

**Comment by xkazama-yukio3** [comment]
対応完了。
