### ISSUE TITLE
Entity検索画面、検索結果の件数のデフォルト値を設定ファイルにて設定可能に

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#113]
Entity検索画面、検索結果の件数のデフォルト値を設定ファイルにて設定可能に。
デフォルトから変更したい場合、EntityView定義で毎回設定するのがつらい。
GemService（でいいか？ViewSerice？）でEntityViewのデフォルト値を指定可能にする。

**Comment by houshiPLAss** [comment]
対応完了。
