### ISSUE TITLE
参照プロパティの新規ボタン、追加ボタンの表示制御

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#114]
参照プロパティの新規ボタンが効かない場合(多重度分設定されてる)、新規ボタンを非表示にしてほしい。
という要望。

これ以上の追加などの操作できない状況の場合には、
新規ボタン、追加ボタン（ネストテーブル）を消すようにする。

**Comment by houshiPLAss** [comment]
対応完了。
