### ISSUE TITLE
EQLの関数にsin,cos,acosなどの算術関数を追加

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#1148]
EQLの関数に算術関数を追加

## 追加関数

- SIN
- COS
- TAN
- ASIN
- ACOS
- ATAN
- ATAN2

**Comment by xsekiguchi** [comment]
( _English_ )

Added arithmetic functions to EQL functions

## Additional Functions

- SIN
- COS
- TAN
- ASIN
- ACOS
- ATAN
- ATAN2
