### ISSUE TITLE
gem、検索一覧で、多重度複数のプロパティではソートできないようにする

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#1152]
gem、検索一覧で、多重度複数のプロパティではソートできないようにする。
検索一覧で、多重度複数のプロパティでソートするとバイナリ型だとエラー、それ以外だと無意味なソートとなる。

**Comment by xkazama-yukio3** [comment]
_(English)_
In gem, it is not possible to sort by multiple multiplicity properties in the search screen.
When sorting by multiple properties in the search screen, an error occurs if the property is a binary type, otherwise the sorting is meaningless.
