### ISSUE TITLE
EntryPointBuilder、serverRoleを指定した場合の挙動が不正

### ISSUE THREAD

**Issue by yumaishida** [ISID/iPLAss#1165]
EntryPointBuilder、serverRoleを指定した場合の挙動が不正。
serverRoleを指定した場合に、serverIdとして反映されてしまっている。

**Comment by HiguchiKiyoshi** [comment]
_(English)_
In EntryPointBuilder, the behavior when serverRole is specified is incorrect.
When specifying serverRole, it is reflected as serverId.
