### ISSUE TITLE
gem、フラットスキンにてReferencePropertyEditorの参照ツリー表示時の選択状態が判別できない

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#1166]
gem、フラットスキンにてReferencePropertyEditorの参照ツリー表示時の選択状態が判別できない

**Comment by xkazama-yukio3** [comment]
_(English)_
In gem, when using a Flat skin, the selection state of the reference tree in the ReferencePropertyEditor cannot be determined.
