### ISSUE TITLE
ReadOnlyトランザクションの挙動の改善

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#1172]
ReadOnlyトランザクションの挙動の改善。
ReadOnly指定してしまうと、同一リクエスト内で、ResourceHolderで確保したRead/WriteなConnectionと別にConnectionをもう一つ確保する。リードレプリカある環境だとそれでOKだが、ない環境の場合マスターに対して2本のConnectionを確保することになる。
このあたりをうまく解決できる仕組みを検討する。
宣言的にコーディングされたReadOnly指定を実行時には指定なしと同じにできる仕組み。

**Comment by xsekiguchi** [comment]
## 対応
- ReadOnly の場合に新規にコネクションを作成するかを判定フラグを追加し、コネクション作成時に確認する
- ServiceConfig の指定によりフラグを変更可能とする

**Comment by xsekiguchi** [comment]
(_English_)

Improved read-only transaction behavior

## Improvement details

- Add a flag to determine if a new connection should be created for read-only and check when creating a connection.
- Flag can be changed by specifying ServiceConfig.
