### ISSUE TITLE
GEM、大量データ用参照セクション、削除処理で既に削除されている場合にNullPointerExceptionが発生する

### ISSUE THREAD

**Issue by yumaishida** [ISID/iPLAss#1179]
GEM、大量データ用参照セクションの削除処理で、対象データが削除されているとNullPointerExceptionが発生する。
削除されているかをチェックして、Exceptionを発生させないようにする。

削除されている場合は、削除処理をスキップした上で、正常ステータスを返却し、セクションを再描画させる。

**Comment by xkazama-yukio3** [comment]
_(English)_
In GEM, NullPointerException is occured if the target data is deleted in the deletion process of the mass reference section.
Check to see if it has been deleted and avoid generating an Exception.

If it has been deleted, skip the deletion process, return a normal status, and have the section redrawn.
