### ISSUE TITLE
WebFrontendService、WebAPI定義のデフォルトキャッシュ設定も設定可能に

### ISSUE THREAD

**Issue by yumaishida** [ISID/iPLAss#1205]
WebFrontendService、WebAPI定義のデフォルトキャッシュ設定も設定可能にする。
`defaultCacheControlType` という設定項目名とする。デフォルトは未設定とする。

**Comment by HiguchiKiyoshi** [comment]
_(English)_
WebFrontendService, WebAPI definition default cache settings can also be set.
Name the setting item `defaultCacheControlType`. Default is unset.
