### ISSUE TITLE
アノテーションでWebApi定義を設定する際、CacheControlTypeを「CACHE_PUBLIC」にしても反映されない

### ISSUE THREAD

**Issue by yumaishida** [ISID/iPLAss#1207]
アノテーションでWebApi定義を設定する際、CacheControlTypeを「CACHE_PUBLIC」にしても反映されない

**Comment by HiguchiKiyoshi** [comment]
_(English)_
When setting the WebApi definition with annotation, it is not reflected even if CacheControlType is "CACHE_PUBLIC"
