### ISSUE TITLE
Referenceプロパティエディタ、name以外のプロパティをラベルとして扱うことを可能に

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#121]
Referenceプロパティエディタ、Entityのname以外のプロパティをラベルとして扱うことを可能に。
表示タイプ別に対応が必要。

**※このissueは表示タイプがLink、Selectのパターンを対応するのみです。**

**Comment by houshiPLAss** [comment]
対応完了。

**Comment by houshiPLAss** [comment]
・表示タイプがLinkの場合、検索画面でリファレンスプロパティの表示ラベルは正しくない
・多重度が１より大きいかつレベルとして扱うプロパティ定義が存在する場合、詳細画面表示にエラーが発生する。

**Comment by houshiPLAss** [comment]
対応完了。
