### ISSUE TITLE
CKEditorバージョンアップ

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#1222]
CKEditorバージョンアップ。4系最新に。

### Compatibility notes

CKEditor をバージョンアップします。（ 4.14.0 -> 4.22.1 )
お知らせ情報エンティティのお知らせ内容および、LongText, String 型のプロパティを RICHTEXT の表示タイプで利用している場合、互換性の問題が発生する可能性があります。
CKEditor 4.21 より iframe 要素には sandbox 属性が付与されます。

以下の CKEditor 設定の説明をご確認ください。

- iframe_attributes - https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-iframe_attributes
- embed_keepOriginalContent - https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-embed_keepOriginalContent

**Comment by xsekiguchi** [comment]
( _English_ )

CKEditor version up to the latest version 4.

### Compatibility notes

Upgrade CKEditor. ( 4.14.0 -> 4.22.1 )
If you are using the LongText, String type properties and the contents of announcement of information entity with the RICHTEXT display type, there is a possibility of compatibility issues.

Please check the following CKEditor configuration instructions.

- iframe_attributes - https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-iframe_attributes
- embed_keepOriginalContent - https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-embed_keepOriginalContent
