### ISSUE TITLE
検索条件がHTMLエンコードされる

### ISSUE THREAD

**Issue by yoshiharuyasuda** [ISID/iPLAss#123]
検索条件に全角で入力し、検索結果から詳細画面やごみ箱へ遷移、その後検索画面に戻ってくると、検索条件の値がHTMLエンコードされた状態で設定されている。
またHTMLエンコード後の文字列を使った検索が行われ、検索結果が再現できない。

**Comment by houshiPLAss** [comment]
CE側は対応不要。

**Comment by xkazama-yukio3** [comment]
EE側は3.0.6にて対応。
