### ISSUE TITLE
RequestRestriction、allowMethodsでワイルドカードが指定された場合のCORS処理の考慮漏れ

### ISSUE THREAD

**Issue by yumaishida** [ISID/iPLAss#1253]
RequestRestriction、allowMethodsでワイルドカードが指定された場合、CORSの許可メソッド（Access-Control-Allow-Methods）の考慮が足りておらず、ワイルドカードをそのまま値として返してしまっている。
ワイルドカードを具体的なメソッド名のリストに置換するよう修正する。

**Comment by xsekiguchi** [comment]
( _English_ )

When wildcards are specified in RequestRestriction and allowMethods, the CORS allow methods (Access-Control-Allow-Methods) are not fully considered and the wildcards are returned as is.
Fix to replace the wildcard with a list of concrete method names.
