### ISSUE TITLE
gem、BinaryPropertyEditorにてアップロード可能なmimeTypeを指定可能にする

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#1262]
gem、BinaryPropertyEditorにてアップロード可能なmimeTypeを指定可能にする。
現状、EntityのBinary型で指定可能なacceptMimeTypesPatternをView単位で制御可能にする。
GemConfigServiceでの一律の設定も可能にする。

**Comment by xsekiguchi** [comment]
( _English_ )

Enable specification of mimeType that can be uploaded by gem and BinaryPropertyEditor.
Enable control of acceptMimeTypesPattern, which can currently be specified with Entity's Binary type, on a per-view basis.
Enable uniform setting by GemConfigService.
