### ISSUE TITLE
新規登録/編集時の表示可否改善（標準セクション、参照セクション）

### ISSUE THREAD

**Issue by yoshiharuyasuda** [ISID/iPLAss#1293]
AdminConsoleのDetailLayoutで、標準セクション、参照セクションをD＆Dした際に、新規登録/編集時の表示可否にINSERTが設定されてしまう。
（標準ロードでは未指定）
そのまま利用すると編集画面で追加したセクションが表示されなくなる。

**Comment by HiguchiKiyoshi** [comment]
_(English)_
In the DetailLayout of the AdminConsole, when a standard or reference section is dragged and dropped, INSERT is set as the visibility for registration/editing.
If used as is, the added section will not be displayed on the editing screen.
