### ISSUE TITLE
AdminConsole、BinaryTemplateの画像がプレビュー表示されない

### ISSUE THREAD

**Issue by xkazama-yukio3** [ISID/iPLAss#1327]
AdminConsole、BinaryTemplateの画像がプレビュー表示されない。

BinaryタイプのTemplate編集画面で、画像を保存した際に、プレビューが表示されず、
405エラーが返ってくる。

**Comment by rikouki-isid** [comment]
_( English )_

AdminConsole's binary images of the template cannot be previewed.

The image in the preview area cannot be displayed, though a binary type image of the Template Attribute editing dialog are saved.
A 405 error is returned.
