### ISSUE TITLE
gem、NestTableにて連動プロパティを設定可能にする

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#1329]
NestTableにて `連動プロパティ` を設定可能にする。

現状、NestTableのReferencePropertyEditorに対して `連動プロパティ` を保存することができないので可能にする。

あわせて、
- NestTable内での連動を可能にするため、 `ネストプロパティ同士の連動` プロパティを追加する。

検索条件については、連動側(To)のタイプが `Select` 形式のみサポートされているため、
ドキュメントに記載する。

**Comment by xkazama-yukio3** [comment]
_(English)_
Enable setting of `link property` in NestTable.

Currently, it is not possible to save `link property` in NestTable's ReferencePropertyEditor, so make it possible.

In addition
- For enable linkage within NestTable, add `Link with nested properties` .

For search conditions, only the `Select` type is supported for the link target property (To),
the documentation should clearly state this.
