### ISSUE TITLE
Message定義、更新した場合の並び順を保持する

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#139]
Message定義、更新した場合の並び順を保持する。
メタデータXMLで差分比較する場合、つらい。

**Comment by xkazama-yukio3** [comment]
メタデータのgetter、setterをMapインターフェースにできるようにする。

**Comment by xkazama-yukio3** [comment]
一旦、MapをLinkedHashMapに変更した状態でリリース。
