### ISSUE TITLE
Entity編集画面、キャンセル押下時の戻り先画面の改善

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#173]
Entity編集画面、キャンセル押下時の戻り先画面の改善。

現状、キャンセル時の戻り先画面は固定で一覧画面となっているが、
これを遷移元により戻り先を変える。
- 一覧画面から編集リンクで遷移の場合、一覧画面へ戻る
- 詳細画面から編集リンクで遷移の場合、編集画面へ戻る

**Comment by houshiPLAss** [comment]
対応完了。

**Comment by houshiPLAss** [comment]
カスタム詳細表示アクション定義が存在するパターンを考え漏れたので、修正します。
対応完了。

**Comment by houshiPLAss** [comment]
・Entity定義だけでView定義してない場合、nullpointerエラーが発生するため、リオープンします。

**Comment by houshiPLAss** [comment]
バグ対応完了。
