### ISSUE TITLE
ネストテーブルで多重度*の時、行追加時にボタンが消える

### ISSUE THREAD

**Issue by yoshiharuyasuda** [ISID/iPLAss#178]
参照項目(多重度*)をネストテーブル表示した際に、追加ボタンを押すと1行追加時点で追加ボタンが消えてしまう。

ReferencePropertyEditor_Table.jspで「toggleAddBtn_xxx」のjsのfunctionを作成する際にプロパティの多重度を見てるが、*だった場合は多重度が-1になり、必ず非表示の判定になる。

#114 の対応。

**Comment by houshiPLAss** [comment]
参照エンティティプロパティエディターだけで多重度設定値が＊(-1)のパターンに対して対応漏れでした。
