### ISSUE TITLE
全文検索、DB（Entity）検索と組み合わせる場合の適用順を変えたメソッドを提供

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#187]
全文検索、DB（Entity）検索と組み合わせる場合の適用順を変えたメソッドを提供する。

現状、contains句でEQL文中に全文検索の結果を組み込みDB検索することが可能。
処理順的には以下。
1. contains句のキーワードで全文検索実行。
2. contains句をoidのin句に変換。
3. EQL（SQL）をDBへ発行。

最初に全文検索結果（limit制限あり）で絞り込まれる。

これとは逆に、
まずEQLを発行後に、全文検索結果でフィルターするメソッドも別途提供する。

**Comment by houshiPLAss** [comment]
実装仕様を以下のように変更

- luceneから全文検索条件でoid全部取得します。
- EQLのqueryをcopyしでLimitなしでEQL実行
- コールバックの関数で最大件数、offsetなど処理を実施しデータをリストにセットします。
- SearchOptionの設定ありかつisCountTotalがtrueのみ、最後の件まで総件数の積み上げ処理を実行します。
- データリストを返します。

**Comment by houshiPLAss** [comment]
対応完了。
