### ISSUE TITLE
TenantManager(GUI)、SettingsのJDBCDriver名が正しく表示されない

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#191]
TenantManager(GUI)、SettingsのJDBCDriver名が正しく表示されない

**Comment by xkazama-yukio3** [comment]
以前は、Settingsで接続先を切り替えられるようにしよとしてComboBox形式で表示していたが、
MySQLのJDBCドライバが変更になったため選択値に該当がなく先頭のOracleJDBCドライバが選択された状態になっていた。
現状、Settingsでの切替は行わないようにしたので、単純にテキスト表示に変更する。
