### ISSUE TITLE
ReferenceComboSettingのソートアイテムに参照元のプロパティが表示されてしまう

### ISSUE THREAD

**Issue by houshiPLAss** [ISID/iPLAss#195]
参照プロパティエディターのReferenceComboSettingでソートアイテムに参照元のエンティティのプロパティを表示していますが、参照先のものを表示すべきです。

**Comment by xkazama-yukio3** [comment]
ReferenceComboSettingの `propertyName` で指定されたReferencePropertyが対象にするEntityのプロパティを表示する必要がある。

同じクラス内でトリガーとなるプロパティ(この場合は `propertyName` )を指定できるように、MetaFieldInfoに `soruceEntityNameField` を追加。

> inputTypeがPropertyの場合、対象のEntity名を表すプロパティ名
> 指定されたPropertyのProperty定義から対象のEntityを決定する。
> 同じClass内で参照する場合に指定
>
> String soruceEntityNameField() default "";
