### ISSUE TITLE
連動プロパティの連動元プロパティ名に参照先のプロパティが表示されてしまう

### ISSUE THREAD

**Issue by houshiPLAss** [ISID/iPLAss#199]
Referenceエディターの連動プロパティの設定で、連動元プロパティ名に参照先のプロパティが表示されてしまいます。
参照元のものを表示すべきです。

**Comment by xkazama-yukio3** [comment]
ReferencePropertyEditor内でのPropertyが参照先のProperty指定になっているため、RootのEntityを対象にできるように、MetaFieldInfoに `useRootEntityName` を追加。

> inputTypeがPropertyの場合、childEntityNameで指定されたEntity名を無視してルートのEntity名を利用するか
> 指定された場合のみ、PropertyはルートのEntityが対象になる
> 
> boolean useRootEntityName() default false;
>
