### ISSUE TITLE
一括更新、複数項目を指定して一括更新することを可能に

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#209]
一括更新、複数項目を指定して一括更新することを可能に。
現状、更新したい項目を一つ選択して更新する形式だが、
更新する項目を複数指定して、その複数項目の値を一括で更新させたい。

一括更新用に定義されたEntityView定義にて、一括更新ダイアログの項目、レイアウトを設定可能にする。また詳細画面同様、カスタムスクリプト、テンプレートの埋め込みも可能にする。

**Comment by HiguchiKiyoshi** [comment]
追加要件
- カスタムスクリプトでは検索画面に設定されている項目の値を参照したい

**Comment by houshiPLAss** [comment]
一旦close。
