### ISSUE TITLE
参照プロパティでJoinPropertyEditorを利用する場合、編集ダイアログのプロパティリストに参照元のものが表示されてしまう

### ISSUE THREAD

**Issue by houshiPLAss** [ISID/iPLAss#215]
参照プロパティでJoinPropertyEditorを利用する場合、編集ダイアログのプロパティリストに参照元のものが表示されてしまう。

- 参照プロパティでJoinPropertyEditorを設定しておく。
- 一番目のプロパティエディターをReferenceEditorにしておく。
- ReferenceEditorの編集ボタンを押下し、編集ダイアログでプロパティリストに参照元のものが表示されてしまう。

新規でプロパティを追加する場合は正常に参照先のプロパティが表示されているが、保存されているView定義を開いた場合に参照元のプロパティが表示される状態になってしまう。

**Comment by xkazama-yukio3** [comment]
プロパティを表現するNestPropertyについて、
- JoinPropertyEditorでのプロパティ指定時は、参照元のPropertyが表示したい
- ReferencePropertyEditorのNestTable形式として入力する際は、参照先のPropertyが表示したい

といった２つの要求があるが、NestProperty側では指定のしようがない。
このため現状はもともと用途としてあったReferencePropertyEditorのNestTableとしてのNestPropertyとして参照先のPropertyを表示している状態になっている。

**Comment by xkazama-yukio3** [comment]
画面定義の復元時に、ReferencePropertyに対してJoinPropertyEditorが選択できることを考慮できていなかったため参照先Entity名が渡せていなかった。
