### ISSUE TITLE
ユニークキーの入力フィールドを伴うReferencePropertyEditor

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#219]
ユニークキーの入力フィールドを伴うReferencePropertyEditorを提供する。

[　　　　　　] [選択] 名称

のような形式。
入力フィールドに値を入力してフォーカスアウトで検索して名称表示。
[選択]ボタンでは、検索ダイアログを表示。

**Comment by houshiPLAss** [comment]
一旦close.
