### ISSUE TITLE
gem、EntityView定義、表示項目を動的に制御可能に

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#228]
gem、EntityView定義、表示項目を動的に制御可能に。

現状、EntityView定義で表示するレイアウトや項目を変更したい場合、複数の定義を作成する必要がある（たとえ１つの項目の違いであっても）。
これの設定を簡易化するため、
同一View定義内で、それぞれの項目の表示条件をGroovyScriptで設定できるようにする。
（合わせて、adminConsoleのView定義画面で、同一プロパティのドロップを禁止しているが、その制約を外す）

**Comment by HiguchiKiyoshi** [comment]
検索結果の一覧もできれば

**Comment by HiguchiKiyoshi** [comment]
更新・登録処理において、その項目が更新可能項目か否か判断する処理にも、この表示条件を適用するようにする

**Comment by xkazama-yukio3** [comment]
_(English)_
gem, display items of `EntityView` definition can be controlled dynamically.

Currently, if you want to change the layout and items displayed in the `EntityView`, 
you need to create multiple `FormViews` (even if there is a difference in one item).

To simplify this setting,
enable to set the display condition of each item in GroovyScript within the same `FormView` definition.
(Also, in the AdminConsole view definition screen, dropping the same property is prohibited, but the restriction is removed.)
