### ISSUE TITLE
コピー時にShallowかDeepを選択用のJavaScriptが正しく動かない

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#23]
現状、コピー対象の枚挙クラスorg.iplass.mtp.view.generic.DetailFormView.CopyTargetの変数が英語の全大文字で定義されていてinput hiddenに出力されいますが、Javascript側の判断処理で利用する文字列と一致していません。

例

- サーバ側：DEEP
- JavaScript側：Deep

**Comment by houshiPLAss** [comment]
対応完了
