### ISSUE TITLE
AdminConsole、Entity編集画面改善（SelectValue、Referenceプロパティから別画面へ遷移）

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#252]
エンティティ編集画面のプロパティでSelect型を選択した場合に、GlobalSelectValueを別タブで表示するボタンが欲しい（アクション編集画面から→コマンド、テンプレートに遷移できるのと同様な感じに）。
合わせて、Reference型の場合も別エンティティ編集画面を表示することもできるように。

**Comment by HiguchiKiyoshi** [comment]
_(English)_
I want a button to display GlobalSelectValue in a separate tab when I choose the Select type in the properties of the entity edit screen (in the same way as I can transition from the action edit screen to a command or a template).
In addition, it is possible to display another entity edit screen in case of Reference type.

**Comment by HiguchiKiyoshi** [comment]
Entityのパネルのプロパティ一覧からリンクする形か？
ただ、グリッドにボタンとか置くと描画が重くなる（メニューアイテム）イメージがあるので、プロパティが多い場合に余計に重くならないかが気になるところ。

**Comment by xkazama-yukio3** [comment]
* プロパティ一覧の最後にリンクアイコン表示
* あわせてSelectプロパティでGlobalが選択されている場合はRemarkにSelectValueのnameを表示
