### ISSUE TITLE
gem、一括削除および一括更新のコミット件数を設定可能にする

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#260]
gem、一括削除および一括更新のコミット件数をそれぞれ設定可能にする。
現状、100件単位でコミットしているが、この件数を設定可能なようにする。
（CSVアップロード時と同様のコミット制御をおこなう）

具体的な対応
一括削除、一括更新それぞれの処理に対して、
* EntityView定義に処理時のトランザクション制御タイプ（一括コミット、分割コミット）を指定可能に
* GemConfigServiceに分割コミット時の件数を指定可能に

**Comment by houke4743** [comment]
(English)
Make it possible to set the commit batch size of bulk-update and delete-all on gem.
Currently the batch size is fixed to 100 unit, make it configurable.
(Similar to the commit control of CSV upload )

Details
For each of delete all and bulk update,
- Should be possible to specify the transaction type (all in one/split in divisions) at EntityView definition page.
- Being able to specify the batch size when using "split in division" type of transaction.
