### ISSUE TITLE
NestTableにダイアログの内容を反映させる際にJSエラー

### ISSUE THREAD

**Issue by yoshiharuyasuda** [ISID/iPLAss#290]
参照項目があるNestTableで、編集リンクからダイアログを立ち上げ、編集・保存をすると、Javascriptエラーが発生。
反映先の参照の選択ボタンから属性値を取る際のキーが「propName」等になっているが、設定されている属性値は「data-propName」となっており、値がうまく取れていない。

**Comment by houshiPLAss** [comment]
Javascript error occurs when edit and save item in reference item in NestTable by opening dialog from edit link.
The key for getting the attribute value from the selection button of the reference target is “propName” etc., but the attribute value is set as 「data-propName」 , the value is not gotten correctly.
