### ISSUE TITLE
デフォルト提供のMailTemplateのIDが重複

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#295]
デフォルト提供のMailTemplateのIDが重複。
id=MT0003
で
mtp/auth/onetime/SendCode (EE側に存在するMailTemplate)
mtp/auth/CredentialResetWithSpecifiedPasswordMail
の2つのテンプレートが登録されてしまっている。

mtp/auth/CredentialResetWithSpecifiedPasswordMail
のIDを変更する。

**Comment by houshiPLAss** [comment]
_(English)_
The id of default MailTemplate is duplicated.
id = MT0003 is used both in 
「mtp/auth/onetime/SendCode (exsits in EE MailTemplate)」
and
「mtp/auth/CredentialResetWithSpecifiedPasswordMail」.

Change the id of 「mtp/auth/CredentialResetWithSpecifiedPasswordMail」
