### ISSUE TITLE
gem、大量データセクションの検索時にフックポイントを提供する

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#296]
gem、大量データセクションの検索時にフックポイントを提供する。

SearchQueryInterrupterと同等の形式で提供。

**Comment by xkazama-yukio3** [comment]
_English_

Gem, Provides a hook point when searching for MassReferenceSection and NestTable mode of ReferencePropertyEditor.

Provides the same function as SearchQueryInterrupter.

**Comment by xkazama-yukio3** [comment]
NestTableについては、詳細画面表示時、編集画面表示時に
DetailLayoutに設定された `LoadEntityInterrupter` の `beforeLoadReference` `afterLoadReference` を `LoadType=VIEW` で１件ごとに呼び出しているため対応済みとする。

https://iplass.org/docs/developerguide/genericentitymanager/entityview/index.html#GemCustomize_Load
