### ISSUE TITLE
gem、一括更新および一括削除、更新対象の絞りこみを行えるフックポイントを提供する

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#297]
gem、一括更新および一括削除、更新対象の絞りこみを行えるフックポイントを提供する。
Interrupterに更新対象のoidのリストを引数とした通知メソッドを提供。

**Comment by houshiPLAss** [comment]
Interrupterに一括操作対象のエンティティのリストを引数とした通知メソッドを提供。
エンティティにoid、バージョン、更新日時が設定されています。

**Comment by houshiPLAss** [comment]
_(English)_
Provide hook points that can perform gem, batch update and delete, and narrow down the update target.
Provide a notification method that takes a list of oids to be updated as an argument to Interrupter.
