### ISSUE TITLE
テナント定義（メタデータ）のデフォルト値をmetadata.xmlに定義する

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#298]
テナント定義（メタデータ）のデフォルト値をmetadata.xmlに定義する。
合わせて、Tenant作成ツールではテナント定義を都度新規生成せず、デフォルト定義を利用するようにする。

**Comment by HiguchiKiyoshi** [comment]
テナント生成時、デフォルト値から変更するような設定があるかの確認が必要

**Comment by xwada** [comment]
CUI版の対応が必要

**Comment by xwada** [comment]
(English)

Define default value of tenant definition (metadata) in metadata.xml.
In addition, Tenant creation tool does not create a new tenant definition each time, but uses default definition.
