### ISSUE TITLE
参照セクションで参照項目の名前が取得できない

### ISSUE THREAD

**Issue by yoshiharuyasuda** [ISID/iPLAss#302]
参照セクションに配置した参照項目で、選択画面からデータを選択した際に名前が取得できない。
ネストテーブルや通常の参照は問題なし。

**Comment by houshiPLAss** [comment]
_(English)_

With reference items placed in the reference section, the name cannot be obtained when data is selected from the selection screen. Nested tables and normal references have no problem.
