### ISSUE TITLE
NestTableのバイナリ型で動作不良

### ISSUE THREAD

**Issue by yoshiharuyasuda** [ISID/iPLAss#318]
NestTable内のバイナリ型でファイルアップロードを行うと、非表示のダミー行にファイルが追加される。

addNestRow内でpnameの値を置換（Dummyからidx）しようとしてるが、実際の属性名がdata-pnameなため、置換がうまく行っていない。

**Comment by houshiPLAss** [comment]
_(English)_
When uploading a file with binary type in NestTable, the file is added to the hidden dummy line.

When replace the value of pname in addNestRow (from dummy to idx), but the actual attribute name is data-pname, so the replacement is not successful.
