### ISSUE TITLE
JoinPropertyEditorを利用した場合のValidationエラーメッセージの表示位置を制御可能に

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#329]
JoinPropertyEditorを利用した場合のValidationエラーメッセージの表示位置を制御可能に。

JoinPropertyEditorを利用した場合のValidationエラーメッセージの表示位置に関し、
それぞれのフィールドの下にでるようになっているが、
フィールドは横並びのまま下にエラーメッセージがまとまって表示されるように
設定で切り替えられるようにしたい。

**Comment by houshiPLAss** [comment]
_(English)_
Control the display position of Validation error message when JoinPropertyEditor is used.

Regarding the display position of Validation error message when JoinPropertyEditor is used,
Validation error messages are displayed under their respective field,
add a new config setting that make it possible to control whether display Validatiaon error messages in one place together under fields or not.
