### ISSUE TITLE
ActionおよびWebAPI、クライアントキャッシュの種別にCACHE_PUBLICを追加

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#345]
ActionおよびWebAPI、クライアントキャッシュの種別にCACHE_PUBLICを追加。
CACHE_PUBLICの場合、"Cache-Control: public, max-age=..." が設定される。

**Comment by houshiPLAss** [comment]
_(English)_
Add CACHE_PUBLIC to the list of client-cache type in Action and WebAPI.
"Cache-Control: public, max-age=..." is set if CACHE_PUBLIC is used.
