### ISSUE TITLE
TopView、検索結果一覧パーツの英語文言不正

### ISSUE THREAD

**Issue by xkazama-yukio3** [ISID/iPLAss#362]
TopView、検索結果一覧パーツの英語文言がおかしい。
「検索画面を表示する」が「Search」になっている。

**Comment by HiguchiKiyoshi** [comment]
「To The Search Page」に修正

**Comment by xkazama-yukio3** [comment]
_(English)_
The English wording of SearchResultList parts in TopView is incorrect.
“To The Search Page” is set to “Search”.
