### ISSUE TITLE
TopView、検索結果一覧パーツ、Viewのデフォルトフィルタ条件が効かない

### ISSUE THREAD

**Issue by xkazama-yukio3** [ISID/iPLAss#364]
TopView、検索結果一覧パーツ、Viewのデフォルトフィルタ条件が効かない。

Filter未指定時にも、「デフォルト検索条件をフィルタ定義と一緒に利用するか」がONでないと設定されない。

**Comment by HiguchiKiyoshi** [comment]
Filter未指定の場合にはデフォルトフィルタ条件を適用する

**Comment by xkazama-yukio3** [comment]
フィルタ指定時については、
「デフォルト検索条件をフィルタ定義と一緒に利用するか」がONの場合は適用する。

**Comment by xkazama-yukio3** [comment]
_(English)_
In the SearchResultList part of TopView, the default filter condition does not work.

Even when Filter is not specified, it is not set unless "Whether default filter conditions are used together with filter definition" is ON.
