### ISSUE TITLE
TopView、検索結果一覧パーツ、非同期での検索を可能に

### ISSUE THREAD

**Issue by xkazama-yukio3** [ISID/iPLAss#367]
TopView、検索結果一覧パーツ、非同期での検索を可能に。

現状は同期で検索しているので、非同期で検索するかのフラグを追加して対応する。
（TopViewをカスタマイズしている場合に、影響を与えないように）

**Comment by xminagawa** [comment]
_(English)_
Enable asynchronous search in TopView and search result list parts.

Currently, the search is synchronous, so add a flag to indicate whether the search is asynchronous or not.
(To avoid affecting TopView if it is customized)
