### ISSUE TITLE
メニューの表示名、メニュー定義の表示名を利用可能に

### ISSUE THREAD

**Issue by xkazama-yukio3** [ISID/iPLAss#375]
メニュー切り替えで表示されるメニューの表示名をメニュー定義の表示名を出力することを可能にする。

現状はロール名を表示している（DEFAULTはDEFAULT固定）が、多言語対応など、Menu定義の表示名を利用できるようにする。

既存の動作を考慮してフラグで制御。
・デフォルトOFF
・AdminConsoleから新規で作成するタイミングではON

フラグがOFFまたは表示名未設定の場合は、現状通りロール名を表示する。

**Comment by isid-maxingguo** [comment]
(English)
It is possible to be displayed  the display name of the menu definition at switching the menu.

Currently, the role name is displayed (DEFAULT is fixed to DEFAULT), but the display name defined in Menu can be used, such as multilingual support.

Controlled by a flag in consideration of existing operation.
・ Default OFF
・ ON when newly created from Admin Console

If the flag is OFF or the display name is not set, the role name is displayed as it is.
