### ISSUE TITLE
参照ダイアログからの新規登録時にセクションが非表示にならない

### ISSUE THREAD

**Issue by yoshiharuyasuda** [ISID/iPLAss#379]
標準セクションの「新規登録/編集時の表示可否」をUPDATEに設定したエンティティについて、
参照ダイアログで新規登録をする場合、標準セクションが表示されたままになる。

jspを見るとダイアログじゃない方のjspと表示の条件が違っている。
edit.jsp 270行目

`
if (!EntityViewUtil.isDisplayElement(defName, section.getElementRuntimeId(), OutputType.EDIT)
		|| !ViewUtil.dispElement(section)) {
	continue;
}
`

ref/edit.jsp 221行目

`
if (!EntityViewUtil.isDisplayElement(defName, section.getElementRuntimeId(), OutputType.EDIT)
		&& ViewUtil.dispElement(section)) {
	continue;
}
`

他のセクションについては未確認。

**Comment by houshiPLAss** [comment]
_(English)_
About entities for which UPDATE is set in the standard section 「Display in Create New/Edit」.
If you create a new entry in the Reference dialog, the standard section remains displayed.

The display condition is different from the one of the non-dialog jsp.

`
if (!EntityViewUtil.isDisplayElement(defName, section.getElementRuntimeId(), OutputType.EDIT) || !ViewUtil.dispElement(section)) { continue; }
`

ref/edit.jsp line 221
`
if (!EntityViewUtil.isDisplayElement(defName, section.getElementRuntimeId(), OutputType.EDIT) && ViewUtil.dispElement(section)) { continue; }
`

Other sections is not checked.
