### ISSUE TITLE
javax.activationのバージョン競合

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#381]
javax.activationのバージョンが競合している。

com.sun.mail:javax.mail:1.5.6
 -> javax.activation:activation:1.1

javax.xml.bind:jaxb-api:2.3.1
 -> javax.activation:javax.activation-api:1.2.0

**Comment by xwada** [comment]
(English)
Version conflict of javax.activation.
The versions of javax.activation are in conflict.

com.sun.mail:javax.mail:1.5.6
-> javax.activation:activation:1.1

javax.xml.bind:jaxb-api:2.3.1
-> javax.activation:javax.activation-api:1.2.0
