### ISSUE TITLE
gem、Entityのコピー操作時にバイナリデータ本体はコピーしないモードを指定可能に

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#443]
gem、Entityのコピー操作時にバイナリデータ本体はコピーしないモードを指定可能に。
現状は、コピー操作時に、バイナリデータの実体もコピーしているため、サイズの大きなバイナリデータを保持するEntityの場合、コピーに時間がかかる。

**Comment by houshiPLAss** [comment]
_(English)_
Make it possible to specify a mode in which binary data itself is not copied when copying entities in gem.
At present, the binary data is also copied at the time of the copy operation, so in the case of an Entity having a large binary data, it takes time to copy.

**Comment by houshiPLAss** [comment]
対応完了。
