### ISSUE TITLE
manageLobSizeOnRdbをONで、FileLobStore利用した際にバイナリファイルのコピー処理が著しく遅い

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#444]
manageLobSizeOnRdbをONで、FileLobStore利用した際にバイナリファイルのコピー処理が著しく遅い

**Comment by houshiPLAss** [comment]
_(English)_
When manageLobSizeOnRdb is ON and using FileLobStore, binary file copy processing is extremely slow
