### ISSUE TITLE
EventListener、SendNotificationの宛先が設定できるように

### ISSUE THREAD

**Issue by houke4743** [ISID/iPLAss#456]
"To:"の項目です。EntityのEventListenerで設定項目を追加して、設定できるように。

**Comment by houke4743** [comment]
(English)
Make the SendNotification destination configurable in EventListener dialog.

It is so called the "To:" address.  Add the configurable items in EventListener of Entity, so the To Address can be configured.

**Comment by HiguchiKiyoshi** [comment]
3.0.21でリリースできなかったので、リオープン。
