### ISSUE TITLE
MailTemplate、fromに表示名を設定可能にする

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#458]
MailTemplate、fromに表示名を設定可能にする。
現状、name-addr形式で指定すれば表示名を含むことが可能だが、表示名が日本語の場合はエンコードしたものを設定する必要があり不便のため。

**Comment by xwada** [comment]
(English)
MailTemplate, "from" display name can be set

Currently, it is possible to include the display name if specified in name-addr format, but if the display name is Japanese, it is necessary to set the encoded name, so it is inconvenient.
