### ISSUE TITLE
プロパティエディタ、RichTextの場合で表示モードの場合、ツールバーなどを表示しないことも可能とする

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#461]
プロパティエディタ、RichTextの場合で表示モードの場合、ツールバーなどを表示しないことも可能とする。

**Comment by houshiPLAss** [comment]
_(English)_
In the case of the display mode in the case of the property editor and RichText, it is also possible to hide the toolbar etc.
