### ISSUE TITLE
PermissionExplorer、Tree表示が崩れる

### ISSUE THREAD

**Issue by xkazama-yukio3** [ISID/iPLAss#476]
PermissionExplorer、ActionPermission、WebApiPermissionのTreeのレイアウトが崩れる。
固定列と可変列の高さが一致していない。

**Comment by xkazama-yukio3** [comment]
固定列表示部分は、フォルダアイコン表示部分が22pxあり、可変列の指定高さんの21pxとあわず、ずれてしまっている。

**Comment by HiguchiKiyoshi** [comment]
_(English)_
In PermissionExplorer, the layout of Tree of ActionPermission and WebApiPermission is broken.
Fixed row and variable row do not have the same height.
