### ISSUE TITLE
AutoNumberProeprty、採番単位を制御可能に

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#48]
AutoNumberProeprty、採番単位を制御可能に。

フォーマットを "${entity.type}${nextVal()}"　とした場合、
- A001
- A002
- B003
- C004
- A005

と採番されるが、
- A001
- A002
- B001
- C001
- A003

としたい場合を考慮する。
nextVal()に採番単位の引数を渡せるようにする。

"${entity.type}${nextVal(entity.type)}"

上記のような感じで。

**Comment by xkazama-yukio3** [comment]
対応完了。

**Comment by xkazama-yukio3** [comment]
この対応に伴って、AutoNumberの現在値確認、リセットの方法が変更になっている。
