### ISSUE TITLE
gem、ユーザに言語設定されている場合は、言語選択メニューは表示しない

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#487]
gem、ユーザに言語設定されている場合は、言語選択メニューは表示しない。
（ユーザEntityに明示的に言語が設定されている場合は、言語選択メニューより優先されるため、選択させる意味がない）

**Comment by kimukimu2k20** [comment]
マスターにマージ済み

**Comment by HiguchiKiyoshi** [comment]
_(English)_
In the gem module, if the user has been set the language, the language selection menu will not be displayed.
(If the language has been explicitly set to the user entity, it takes precedence over the language selection menu, so there is no point in having the user select the language)
