### ISSUE TITLE
adminConsole、メニューからEntityViewの参照を把握しやすくする

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#493]
adminConsole、メニューからEntityViewの参照を把握しやすくする。
現状、メニューとEntityView定義の関連性の把握が一覧性が良くないので、改善する。
EntityMenuItemの場合、Menu Tree上にView定義名を表示するようにする。

**Comment by kimukimu2k20** [comment]
マスターにマージ済み

**Comment by HiguchiKiyoshi** [comment]
_(English)_
Make it easier to understand the EntityView reference from the menu definition in adminConsole.
Improve the current grasp of the relationship between menu and EntityView definitions because they are not easy to grasp.
In the case of EntityMenuItem, display the view definition name on the menu tree.
