### ISSUE TITLE
gemの検索画面、詳細画面でEntityレコード単位で編集リンク・ボタンの出し分けを設定可能に

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#497]
gemの検索画面、詳細画面でEntityレコード単位で編集リンク・ボタンの出し分けを簡単に制御でるような設定項目を用意する。
現状で、上記のことを実現するためにはカスタムスクリプトを組む必要があるが、これを簡便にする。

また、Entity権限の更新・削除可能データ範囲により表示制御をするデフォルト実装クラスも提供する

**Comment by HiguchiKiyoshi** [comment]
_(English)_

Easily control setting items for each entity record in the gem's search and detail screens, such as the assignment of edit links and buttons.
In order to achieve the above, it is necessary to write custom scripts, but this should be simplified.

In addition, a default implementation class to control the display of the data which can be updated or deleted by the range of the entity authority is also provided.

**Comment by xkazama-yukio3** [comment]
- 検索画面
1. SearchFormViewに「検索画面Handlerクラス名」を追加（List形式）
`org.iplass.mtp.view.generic.SearchFormViewHandler` を実装したクラス名を指定可能。
カスタムで実装する場合は、gemに特化した `org.iplass.gem.command.generic.search.handler.SearchFormViewAdapter` を継承することを想定。

2. SearchResultSectionに「Entity権限の可能範囲条件で編集リンク表示を制御」設定を追加
チェックされた場合、レコードごとにEntity権限の更新可能範囲条件をチェックし、更新可能な場合のみリンクを表示。
実装は `SearchFormViewHandler` 機能を利用した `CheckPermissionLimitConditionOfEditLinkHandler` で実現。
SearchFormViewで設定されたクラス群の先頭に追加して実行。

- 詳細編集画面
1. DetailFormViewに「詳細編集画面Handlerクラス名」を追加（List形式）
`org.iplass.mtp.view.generic.DetailFormViewHandler` を実装したクラス名を指定可能。
カスタムで実装する場合は、gemに特化した `org.iplass.gem.command.generic.detail.handler.DetailFormViewAdapter` を継承することを想定。

2. DetailFormViewに「Entity権限の可能範囲条件でボタン表示を制御」設定を追加
チェックされた場合、更新対象のデータについてEntity権限の更新可能範囲条件をチェックし、編集、削除ボタンの表示を制御。
実装は `DetailFormViewHandler` 機能を利用した `CheckPermissionLimitConditionOfButtonHandler` で実現。
DetailFormViewHandlerで設定されたクラス群の先頭に追加して実行。


SearchFormViewHandler、DetailFormViewHandler は、一旦最小限でのフックポイントのみ定義。
今後の拡張要件によって改善。
