### ISSUE TITLE
GemAuthに定義されるGEM_ROLESは設定可能にする

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#499]
GemAuthに定義されるGEM_ROLESをGemConfigServiceで設定可能にする。
あくまでデフォルト値は、 `GemUser` 、`AppAdmin` ロールであり、カスタムのロールを追加できるように。

**Comment by xkazama-yukio3** [comment]
_(English)_
Make GEM_ROLES defined in GemAuth configurable with GemServiceConfig.

The default values ​​are `GemUser` and `AppAdmin` roles, so can add custom roles.

**Comment by xkazama-yukio3** [comment]
GemConfigServiceに以下を追加

- permitRolesToGem：Gem許可ロール（デフォルト： `GemUser` 、 `AppAdmin` ）
- permitRolesToNoView：EntityViewが未定義の場合の許可ロール（デフォルト： `AppAdmin` ）

_(English)_
Add the following to GemConfigService.

- permitRolesToGem : Gem permission role (default: `GemUser` , `AppAdmin` )
- permitRolesToNoView : Allow role when EntityView is undefined (default: `AppAdmin` )
