### ISSUE TITLE
プロパティエディタにHidden出力モードを提供

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#500]
プロパティエディタの表示タイプとして、Hiddenを設定可能にする。

検索条件部分や、詳細・編集画面でHiddenとして出力する他、
検索結果の列を非表示にする。

対象は以下とする。

- 各種プリミティブ系のPropertyEditor (※1)
- TemplatePropertyEditor (※2)
- VirtualPropertyItem (※3)

※1 詳細・編集画面における、ReferencePropertyEditorのNestPropertyについては今回は未対応。
　検索条件、検索結果については対応。

※2 検索条件や詳細画面におけるタイトルを含む枠は非表示になるが、出力内容はTempalte内で適切に出力する必要がある

※3 VirtualPropertyItemは指定したEditorの表示タイプにより制御

**Comment by xkazama-yukio3** [comment]
_(English)_
`Hidden` can be set as the display type of the property editor.

In addition to outputting as `hidden` in the search condition part and the details / edit screen,
And hide the search result column.

The target is as follows.

- Property Editor of various primitives (*1)
- TemplatePropertyEditor (*2)
- VirtualPropertyItem (*3)

*1 NestProperty of ReferencePropertyEditor on the details / edit screen is not supported this time.
   Correspondence for search conditions and search results.

*2 The frame including the title on the search conditions and details screen is hidden, but the output content needs to be output properly in Tempalte.

*3 VirtualPropertyItem is controlled by the specified Editor display type.
