### ISSUE TITLE
gem、StringPropertyEditorでinputのtype、patternを設定可能にする

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#502]
StringPropertyEditorで、inputのtypeとpatternを設定可能にする。

- typeの指定は、表示タイプが `TEXT` の場合に可能
- patternの指定は、表示タイプが `TEXT` と `PASSWORD` の場合に可能

併せて、エラー時のメッセージをカスタマイズ可能にする。

**Comment by xkazama-yukio3** [comment]
_(English)_
In StringPropertyEditor, input type and pattern can be set.

- type can be specified when the display type is `TEXT`
- pattern can be specified when the display type is `TEXT` and `PASSWORD`

Customizable error messages.
