### ISSUE TITLE
jqueryライブラリ他、JavaScriptライブラリバージョンアップ

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#505]
jqueryライブラリバージョンアップ。合わせてJavascript系ライブラリをバージョンアップ。

### gem changes
| library | from | to |
| --- | --- | --- |
| org.webjars:jquery | 3.2.1 | 3.5.1 |
| org.webjars:ckeditor | 4.7.3 | 4.14.0 |
| org.webjars:jquery-blockui | 2.70 | 2.70-1 |
| org.webjars:momentjs | 2.18.1 | 2.24.0 |
| org.webjars.npm:free-jqgrid | 4.14.1 | 4.15.5 |
| org.webjars.npm:jqtree | 1.4.2 | 1.4.9 |
| org.webjars.bower:blueimp-file-upload | 9.28.0 | 10.30.1 |
| org.webjars:font-awesome | 5.0.9 | 5.13.1 |

### gem keeps
| library | current |
| --- | --- |
| org.webjars:jQuery-Timepicker-Addon | 1.6.3 |
| org.webjars.bower:jquery-ui | 1.12.1 |
| org.webjars.bower:mediaelement | 4.2.5 |
| org.webjars:pdf-js | 1.9.426 |
| org.webjars.bower:fullcalendar | 3.5.1 |

### gem removes
- org.webjars:select2
- org.webjars.bower:jQuery-contextMenu

**Comment by xkazama-yukio3** [comment]
_(English)_
jquery version up. At the same time, other Javascript libraries have been upgraded.
