### ISSUE TITLE
gemのEntityView、自動生成の際にシステム項目を表示有無を制御可能にする

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#518]
gemのEntityView、自動生成の際にシステム項目を表示有無を制御可能にする。
GemConfigServiceで、
システム項目表示有無、表示するプロパティを設定可能にする。
システム項目表示する場合は、システム項目セクションにて表示するようにする。

**Comment by xkazama-yukio3** [comment]
_(English)_
EntityView of gem, display of system properties can be controlled at the time of automatic generation.

GemConfigService enables the following settings.
- Display of system properties
- Display target property

When displaying system properties, display them in the `System Information` section.
