### ISSUE TITLE
EntityViewの管理設定にてdefault view定義でautoGenerateをtrueにしても自動生成されない

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#520]
EntityViewの管理設定にてdefault view定義でautoGenerateをtrueにしても自動生成されない。
また、
EntityMenuItemのview名プルダウンにおいて、Viewの管理設定で定義されているview名を考慮していないため、選択できない。

**Comment by xkazama-yukio3** [comment]
_(English)_
View is not automatically generated even if the `default` SearchView's autoGenerate is `true` in [View control settings].

Also,
In the `view name` pulldown of [Entity MenuItem settings], cannot be selected the view name defined at only [View control settings].

**Comment by xkazama-yukio3** [comment]
NOTE : 管理設定画面で `default` としてView名を追加していたものは、 `default` というView名に対する設定になっているので注意。デフォルトに対して設定したい場合は、 `(default)` に対して設定するか、 View名を空で追加して設定すること。
