### ISSUE TITLE
EntityViewの管理設定にてdefault view定義でautoGenerateをtrueにしても自動生成されない（3.0）

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#521]
Backport of #520

**Comment by xkazama-yukio3** [comment]
NOTE : 管理設定画面で `default` としてView名を追加していたものは、 `default` というView名に対する設定になっているので注意。デフォルトに対して設定したい場合は、 `(default)` に対して設定するか、 View名を空で追加して設定すること。
