### ISSUE TITLE
更新処理の際にPropertyEditorとEntityのPropertyの型をチェックし意図しない値での更新を防ぐ

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#522]
更新処理の際にPropertyEditorとEntityのPropertyの型をチェックし意図しない値での更新を防ぐようにする。
現状、PropertyEditorの設定とEntityのPorpertyの型に互換性がない場合、意図せずnullで更新されてしまう。
これを、型に互換性がない場合はシステムエラーではじくようにする。
また、
併せて、adminConsoleのcheckState()で不一致を検出可能にする。

**Comment by xkazama-yukio3** [comment]
_(English)_
Check the PropertyEditor and Entity property types during the update process to prevent updates with unintended values.
Currently, if the PropertyEditor type and the Entity's porperty type are incompatible, it will be unintentionally updated with null.

To prevent this, if the types are incompatible, repel with a system error.
Also, at the same time, checkState () of AdminConsole can detect the mismatch.
