### ISSUE TITLE
更新時の表示判定Scriptにentityがバインドされないタイミングがある

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#530]
更新時に呼び出される表示判定Scriptにentityがバインドされないタイミングがある。
DetailCommandContext#createEntity()内で、「createEntity("")」処理の中で判定処理が呼ばれてしまうが、ここではまだEntityが生成できていない。
 このため、各SectionやElementの表示判定スクリプト内でバインドされているentityで判定していると、更新対象にならずに保存されない。
（例えば、entity != null とか、entityのステータスとか）

対応としては、更新処理の先頭で更新対象のEntityをロードしてバインドする。
ロード時のOptionは、詳細画面表示時同様、DetailView定義の「定義されている参照プロパティのみを取得」によって判断。

**Comment by xkazama-yukio3** [comment]
_(English)_
There is a timing when entity is not bound to the `display judgment script` called at the time of update.
In `DetailCommandContext#createEntity()` , the judgment process is called in the `createEntity ("")` process, but the Entity has not been created yet.
Therefore, if it is judged by the entity bound in the `display judgment script` of each Section or Element, it will not be updated and will not be saved.
(For example, entity! = null, entity status, etc.)

As a solution, load and bind the Entity to be updated at the beginning of the update process.
Option at the time of loading is judged by `Get the only reference properties that are defined` of DetailFormView definition as well as at the time of detail screen display.
