### ISSUE TITLE
RegistrationInterrupterで渡されるEntityのSelect型プロパティの値に表示名もセットする

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#532]
RegistrationInterrupterで渡されるEntityのSelect型プロパティの値に表示名もセットする。
現状、画面から入力されたvalueの値のみをセットしている。

併せて、
SelectValueDefinitionManagerにvalue値からSelectValueを簡易に取得可能なメソッドを用意する。

SelectValue getValue(String entityName, String propertyName, String value)

のような形で。

**Comment by xsuzukiyosuke** [comment]
_(English)_
Set the display name also to Select Property of the entity passed to RegistrationInterrupter.
Currently, have been set only the value entered on the screen.

And prepare the method that can get SelectValue from value easily at SelectValueDefinitionManager.

In the form of 
SelectValue getValue(String entityName, String propertyName, String value)
