### ISSUE TITLE
gem、SearchConditionSectionのデフォルトフィルタ条件にRequestContextをバインドする

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#577]
gem、SearchConditionSectionのデフォルトフィルタ条件にRequestContextをバインドする。

大量データ用参照セクションの「絞り込み条件設定スクリプト」も同様に対応する。

**Comment by xkazama-yukio3** [comment]
Bind RequestContext to the `search default condition` of search condition setting.

The `search default condition` of MassReferenceSection corresponds in the same way.

The display name of the setting screen has been changed as follows.

- Search condition setting : `Default filter condition when searching` -> `Search default condition`
- MassReferenceSection : `Filter condition setting script` -> `Search default condition`
