### ISSUE TITLE
PersonalAccessTokenの生成機能

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#585]
gemの「アプリの管理（発行済みTokenのセルフメンテナンス画面）」にPersonalAccessTokenの生成機能を追加する。
内部的にはSimpleAuthTokenを生成する。
※ Tokenの削除/無効化処理をAction->WebAPIに変更

**Comment by yumaishida** [comment]
(English)
Add the functionary of generating a PersonalAccessToken to the application management page (self-maintenance page for issued tokens) of the gem.
Internally, generates a SimpleAuthToken.
