### ISSUE TITLE
検索条件設定のPropertyEditor、LABEL形式をサポートする

### ISSUE THREAD

**Issue by xkazama-yukio3** [ISID/iPLAss#590]
検索条件設定のPropertyEditor、LABEL形式をサポートする。
例えば、現状SelectPropertyEditorでLABELを指定した場合、
SELECT形式と同等の動作となるが、条件設定スクリプトなどによる固定値を明示的に画面に出力可能にする。

**Comment by xkazama-yukio3** [comment]
SelectPropertyEditor以外についても、LABEL形式をサポートできていないものは対応する。

**Comment by isid-maxingguo** [comment]
Supports `LABEL` format for Property Editor on search condition settings.
For example, if you specify `LABEL` in the current `SelectPropertyEditor`,
The operation is the same as the SELECT format, but the fixed value by the condition setting script etc. can be explicitly output to the screen.
