### ISSUE TITLE
gem、DetailLayoutの初期化スクリプトにuserをバインドする

### ISSUE THREAD

**Issue by xkazama-yukio3** [ISID/iPLAss#594]
gem、DetailLayoutの「初期化スクリプト」（新規作成時の初期値設定）にuserをバインドする。
あわせて、SearchLayoutの「デフォルトプロパティ条件設定スクリプト」と同様、リクエスト情報もバインドする。

また「カスタムコピースクリプト」（コピー時のカスタム処理）にもuser、リクエスト情報をバインドする。

**Comment by xkazama-yukio3** [comment]
既にスクリプト側で「user」変数が利用されている場合、
バインドされたUserBindingではなく、スクリプト側の定義が優先されていることを確認すること。

**Comment by isid-maxingguo** [comment]
(English)
Bind user to the "initialization script" (initial value setting at the time of new creation) of gem and DetailLayout.
Also bind the request information as in the "default property condition setting script" of SearchLayout.

Apply such binds of user and request information to the "custom copy script" (custom processing at the time of copying) as well.

If the "user" variable is already used on the script side
Make sure that the script-side definition takes precedence over the bind UserBinding.
