### ISSUE TITLE
RequestContextBindingにgetParam(String)、getParams(String)を定義

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#595]
RequestContextBinding（groovyScript上での読み取り専用RequestContextとの位置づけ）にgetParam(String)、getParams(String)を定義する。
RequestContextとの親和性の向上のため。

**Comment by xsuzukiyosuke** [comment]
_(English)_
Define getParam(String), getParams(String) at RequestContextBinding(Read only-RequestContext on groovyScript).
Because of improved affinity with RequestContext.
