### ISSUE TITLE
AdminConsole、TempleteのPoiOutputLogicの英語説明文言が不正

### ISSUE THREAD

**Issue by xkazama-yukio3** [ISID/iPLAss#600]
AdminConsole、TempleteのPoiOutputLogicの説明文言が不正。

`Please specify the implementation class of org.iplass.mtp.entity.EntityReportOutputLogic.`

正しくは

`Please specify the implementation class of org.iplass.mtp.web.template.report.PoiReportOutputLogic.`

**Comment by isid-maxingguo** [comment]
The description of PoiOutputLogic of Templete in AdminConsole  is incorrect.

Please specify the implementation class of org.iplass.mtp.entity.EntityReportOutputLogic.

The correct description is

Please specify the implementation class of org.iplass.mtp.web.template.report.PoiReportOutputLogic
