### ISSUE TITLE
mysqlのデフォルト提供するDDLからROW_FORMAT指定を削除する

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#603]
mysqlのデフォルト提供するDDLからROW_FORMAT指定を削除する。
別途、
圧縮したい場合用のddlも準備する。
圧縮はTransparent Page Compressionを使う形にする（圧縮効果を期待できるテーブルのみ）。

**Comment by HiguchiKiyoshi** [comment]
ストレージスペース作成DDLの方も対応をする。
useCompressionフラグを渡して制御可能にする。

**Comment by xsuzukiyosuke** [comment]
_(English)_
Delete ROW_FORMAT from DDL provided by default with mysql.
And prepare ddl for compression.
About compression, use Transparent Page Compression(Only table that can be expected to have a compression effect).

Also support the DDL that creates Storage Space.
Make it controllable by a useCompression flag.
