### ISSUE TITLE
ネストテーブルで多重度*の時、行追加時にボタンが消える

### ISSUE THREAD

**Issue by yoshiharuyasuda** [ISID/iPLAss#604]
https://github.com/ISID/iPLAss/issues/178 の対応漏れ。

行追加方法を「TOP」にした場合、ボタンが消えてしまう。
デフォルト（未設定）と「BOTTOM」は#178で問題解消済み。

**Comment by isid-maxingguo** [comment]
(English)
#178 correspondence omission.

When the line addition method is set to `TOP`, the button disappears.
The default (unset) and `BOTTOM` have been resolved with # 178.
