### ISSUE TITLE
ビルトインの認証プロバイダ、パスワードポリシーで制御可能項目の拡充

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#616]
ビルトインの認証プロバイダ、パスワードポリシーで制御可能項目の拡充。
- アカウントIDと同一の値を不許可（デフォルト許可）
- denylistの定義（password、12345などよく使われるフレーズの不許可）

AccountNotificationListenerでカスタムスクリプトを作らずとも、よく実施する上記のようなポリシーを簡単に設定可能に

**Comment by xsuzukiyosuke** [comment]
_(English)_
Expand controllable items at a built-in authentication provider and password policy.
- deny same password as account id(default : allow)
- Define denylist(deny commonly used phrases such as password and 12345)

Make it easy to set policies like the ones you do often without creating a custom script with AccountNotificationListener.
