### ISSUE TITLE
ファイルアップロード、アップロード時にSystemExceptionが発生するとエラーが表示されずローディング中のままになる

### ISSUE THREAD

**Issue by xkazama-yukio3** [ISID/iPLAss#625]
汎用画面のファイルアップロード機能で、
アップロード時にサーバで `SystemException` ( `EntityRuntimeException` ) が発生すると
エラーが表示されずローディング中のままになる。

**Comment by isid-maxingguo** [comment]
(English)
In the file upload function of the general-purpose screen,
A `SystemException` ( `EntityRuntimeException` ) occurs on the server When upload
No error is displayed and it remains loading.
