### ISSUE TITLE
gem、Entity操作画面で保存時に確認ダイアログを表示可能に

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#640]
gem、Entity操作画面で保存時に確認ダイアログを表示可能な設定フラグをServiceConfigに用意する。
もし、保存時に確認ダイアログを出したい場合、そのフラグをONにすることで一律、操作画面に適用することを可能にする。

**Comment by isid-maxingguo** [comment]
(English)

Prepare a setting flag in ServiceConfig that can display a confirmation dialog when saving on the gem or Entity operation screen.
If you want to display a confirmation dialog when saving, you can apply it to the operation screen uniformly by turning on the flag.
