### ISSUE TITLE
Entityデータのインポート、OIDPrefixを指定するとOIDPropery指定された参照先Entityが参照できない

### ISSUE THREAD

**Issue by xkazama-yukio3** [ISID/iPLAss#66]
Package、EntityExplorerを利用したEntityデータのインポートで、OIDPrefixを指定するとOIDProperty指定された参照先Entityが参照できない状態になる。

OIDProperty指定されたEntityデータをインポートする際、インポート時にOIDPrefixを設定した場合にも、OIDPrefixはつかずOIDPropertyの値が設定される。

このEntityを参照している側をインポートする時には、参照情報としてのOIDを設定する際にOIDPrefixが設定されている場合はOIDPrefixを付けてインポートしてしまっている。

■対応

参照先を登録する際に、参照先EntityのOIDProperty設定を確認し、OIDPropertyが設定されている場合はOIDPrefixを付けないように対応する。

**Comment by HiguchiKiyoshi** [comment]
すでに
「参照先を登録する際に、参照先EntityのOIDProperty設定を確認し、OIDPropertyが設定されている場合はOIDPrefixを付けないように対応する。」
の形で実装済み。

アプリからの報告の勘違い。
