### ISSUE TITLE
日付プレビュー表示機能、TopView単位で利用可否を設定可能にする

### ISSUE THREAD

**Issue by xkazama-yukio3** [ISID/iPLAss#660]
日付プレビュー表示機能について、TopView単位（ロール単位）で利用可否の設定を可能にする。
現状はテナント単位でのみ設定が可能（テナントの日付プレビュー表示設定）。

・TopViewに日付プレビュー設定パーツを追加
・パーツが設定されていない場合は、テナントの設定で制御

あわせてダイアログのレイアウトを改善。

**Comment by HiguchiKiyoshi** [comment]
_(English)_
The date preview function can be enabled/disabled for each role.
Currently, it can only be set on a tenant basis (tenant date preview display settings).

- Add date preview setting parts to TopView.
- If the part is not set, it will be controlled by the tenant settings.
- Improved the layout of the date preview settings dialog.
