### ISSUE TITLE
パスワード履歴保持、保持数ではなく保持期間も指定可能とする

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#664]
パスワード履歴保持、保持数ではなく保持期間も指定可能とする。
「過去6か月の間に設定したパスワードを指定できなくする」といったことを可能に。

**Comment by xsuzukiyosuke** [comment]
_(English)_
In password history, not only password history count, password history period can be specified. 
Enable to deny the password that set for the last 6 months.
