### ISSUE TITLE
フラットスキン、大量データ参照セクションで削除ボタンが効かない

### ISSUE THREAD

**Issue by yoshiharuyasuda** [ISID/iPLAss#68]
編集画面表示時に大量データ参照セクションにデータが存在する場合、
個別に選択して削除ボタンを押しても対象が削除されない。

フラットスキンの場合のみ発生。

**Comment by yoshiharuyasuda** [comment]
design.jsの351行目、チェックボックス自体のイベントをキャンセルして、非表示になってるカスタムチェック（pseudo-checkbox）をクリックして擬似的にイベントを起こしてるが、
ここでイベントキャンセルした時にjqgrid側にイベントが伝わらず、選択状態が取得できないものと思われる。
※全選択時と編集画面表示後に描画した場合（追加とかページングで再リロード）はカスタムチェックボックスが適用されてないので正常に動く

**Comment by xkazama-yukio3** [comment]
対応完了。
