### ISSUE TITLE
DateRangePropertyEditor、検索画面でも利用可能にする

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#680]
DateRangePropertyEditor、検索画面でも利用可能にする。

基準日（基準日時）を指定する単一の日付入力フィールドを持ち、
その入力された基準日から、
fromProperty <= 基準日 and toProperty > 基準日
となるEQL条件文を生成する。

**Comment by ShojimaHiroki-2** [comment]
_(English)_
Provided by NumericRangePropertyEditor.

Numerical version of DateRangePropertyEditor.
The minimum value and maximum value are controlled by two properties.
