### ISSUE TITLE
BinaryPropertEditor、画像の場合、ローテートボタン、Viewerを利用可能に

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#692]
BinaryPropertEditor、画像の場合、ローテートボタンの表示と、Image Viewerを利用可能にする。
ローテートボタンは表示している画像を回転できるようにする（保存データは変更されない）。
Image Viewerでは、画像の拡大・縮小、回転、反転を可能にする。

■ローテートボタン

- Editorの設定に `画像表示時に回転ボタンを表示` を追加
- 詳細画面、編集画面で設定可能にする
- 画像のリンクの横にボタンを表示する
- 画像の変更状態は、検索画面、詳細画面、編集画面それぞれを表示している間は保持する

■Image Viewer

- Editorの設定に `画像またはリンククリック時にイメージViewerを利用` を追加
- 検索結果、詳細画面、編集画面で設定可能にする
- 画像リンクをクリックした際は、別タブで表示がONの場合のみ起動。OFFの場合は通常通りダウンロードする
- 画像をクリックした際は、別タブで表示設定によりインラインまたは別タブで起動する
- 画像の変更状態は、検索画面、詳細画面、編集画面それぞれを表示している間は保持する
- 今後新規でBinaryPropertyEditorを設定する場合（標準ロード含む）は、ONの状態をデフォルトとする（既存のものはOFF）

**Comment by xkazama-yukio3** [comment]
_(English)_
Enable Image Viewer for images in BinaryPropertEditor.
The Image Viewer allows you to zoom in / out, rotate, and flip the image.

- Display inline or in an external window (tab), depending on the `Open new tab` settings
- Can be set on the search results, details screen, and edit screen
- The changed state is retained while the search screen, details screen, and edit screen are displayed.

Measures

- Added `Use Image Viewer when clicking an image or link` to Editor settings
