### ISSUE TITLE
gem、メニュー開閉状態の記憶先をsessionStorageにする

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#703]
gem、メニュー開閉状態の記憶先をsessionStorageにする。
IE7等サポートしていた古い時代からセッションCookieだったが、さすがにもうsessionStorageを使う形にする。

**Comment by yoshiharuyasuda** [comment]
(English)
Set the storage destination of gem and menu open / closed state to sessionStorage.
It has been a session cookie since the old days when it supported IE7 etc., but as expected it will use sessionStorage.
