### ISSUE TITLE
AuroraMySQLに最適化したデフォルトのDDLの提供

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#723]
AuroraMySQLに最適化したデフォルトのDDLの提供。
パラレルクエリを実行しやすいように、
・文字列格納カラムをVARCHAR(192)をベースに定義
・パーティション分割しない形
のStorageSpaceを定義

**Comment by xsuzukiyosuke** [comment]
_(English)_
Provide default DDL optimized for Aurora MySQL.
Define the following storage space so that parallel queries can be executed.
・Define string storage column as VARCHAR (192).
・Do not partition.
