### ISSUE TITLE
gem、BulkLayoutを用いた一括更新において、被参照プロパティのNestTableを利用した更新で不具合発生

### ISSUE THREAD

**Issue by yumaishida** [ISID/iPLAss#729]
BulkLayoutを用いた一括更新において、被参照プロパティのNestTableを利用した更新で不具合が発生する。
複数エンティティを一括更新した場合、複数件それぞれに紐づかず、先頭のエンティティに全部紐づいてしまう。

**Comment by ShojimaHiroki-2** [comment]
_（English）_
An update that cites BulkLayout occurs because it is an update that uses the cited NestTable.
Strings, real numbers of strings rather than accessing real numbers
