### ISSUE TITLE
フラットデザイン、検索結果一覧でのReference項目がリンクであることをわかりやすくする

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#733]
フラットデザイン、検索結果一覧でのReference項目がリンクであることをわかりやすくする。
垂直、水平デザイン同様、青色で表示するようにする。

**Comment by ShojimaHiroki-2** [comment]
_（English）_
Flat design, make it easy to understand that the Reference item in the search result list is a link.
As with vertical and horizontal designs, display in blue.
