### ISSUE TITLE
gem、参照ダイアログ表示時に動的にパラメータを指定可能にする

### ISSUE THREAD

**Issue by xkazama-yukio3** [ISID/iPLAss#753]
gem、参照ダイアログ表示時のリクエストに対して、表示タイミングで動的にパラメータを指定可能にする。

現状、ReferencePropertyEditorの設定で、画面表示時に動的にパラメータを指定することができるが、
例えば、現在の他の編集値を渡したい場合などの利用を想定。

**Comment by yoshiharuyasuda** [comment]
_(English)_
Gem allows you to dynamically specify parameters at the display timing for requests when displaying the reference dialog.

Currently, parameters can be specified dynamically when the screen is displayed using the ReferencePropertyEditor settings.
For example, it is assumed to be used when you want to pass the current edit value of another.
