### ISSUE TITLE
gem、フラットスキン、検索画面で検索条件項目が多い場合のスクロール考慮

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#765]
gem、フラットスキンの場合の検索画面で検索条件項目が多い場合に、検索結果表示が見切れてしまうことがある。
検索結果表示の先頭まで移動するなどのスクロール制御が必要。

**Comment by yoshiharuyasuda** [comment]
_(English)_
When there are many search condition items on the search screen for gem and flat skin, the search result display may be cut off.
Scroll control such as moving to the beginning of the search result display is required.
