### ISSUE TITLE
gem、CSVダウンロード時の形式選択ダイアログのCSVダウンロードボタンを目立たせる改善

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#785]
gem、CSVダウンロード時の形式選択ダイアログのCSVダウンロードボタンを目立たせる改善。

カスタムテーマを使用する際には、各スキンのテーマに以下のセレクタを加える。
■Flat
button.dialog-csvdl-btn {
  background-color: [色指定] !important; }
  button.dialog-csvdl-btn:hover {
    background-color: [色指定]!important; }

■Vertical, Horizantal
button.dialog-csvdl-btn {
  background: linear-gradient([色指定] 0, [色指定] 100%); }
  button.dialog-csvdl-btn:hover {
    background: linear-gradient([色指定] 0, [色指定] 100%); }

**Comment by ShojimaHiroki-2** [comment]
_（English）_
Improved to make the CSV download button in the format selection dialog when downloading gem and CSV stand out.

When using a custom theme, add the following selectors to each skin theme.
■ Flat
`button.dialog-csvdl-btn {
background-color: [color specification]! important;}
button.dialog-csvdl-btn: hover {
background-color: [color specification]! Important;}`

■ Vertical, Horizantal
`button.dialog-csvdl-btn {
background: linear-gradient ([color specification] 0, [color specification] 100%);}
button.dialog-csvdl-btn: hover {
background: linear-gradient ([color specification] 0, [color specification] 100%);}`
