### ISSUE TITLE
gem画面、新しいバージョンで更新した場合は更新後のデータを表示する

### ISSUE THREAD

**Issue by yoshiharuyasuda** [ISID/iPLAss#802]
gem画面で、バージョン管理しているエンティティを新しいバージョンで更新した場合、更新したバージョンのデータを表示する。
TIME BASE等では現在有効なデータを再表示しているため、入力した内容を確認しやすくする。

**Comment by HiguchiKiyoshi** [comment]
_(English)_
On the gem's update screen, when a version-controlled entity is updated with a new version, the data of the updated version should be displayed.
Since the currently valid data is re-displayed in TIME BASE, etc., it makes it easier to confirm the entered content.
