### ISSUE TITLE
ごみ箱から削除データ取得時のソート順を削除時の降順にする

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#808]
ごみ箱から削除データ取得時のソート順を削除時の降順にする。
実際には、シーケンスで採番されるPKであるRB_IDでソート。

**Comment by xsuzukiyosuke** [comment]
_(English)_

The sort order when the deleted data is acquired from the Recycle Bin is changed to the descending order when the data is deleted.
Actually, it is sorted by RB_ID which is the PK numbered in the sequence.
