### ISSUE TITLE
EntityExplorerのCUI版の提供

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#821]
EntityExplorerのCUI版の提供。
バッチ等でのデータ連携時に利用可能なように。
（Entity単位でのデータ出し入れを簡単に）

**Comment by xsuzukiyosuke** [comment]
_(English)_
Provides a CUI version of EntityExplorer.
To be available when linking data in batch etc.
(Easy to put in and out data in Entity units)
