### ISSUE TITLE
mysql（aurora）のobj_blobテーブルのindex（pk）の変更

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#831]
mysql（aurora）のobj_blobテーブルのindex（pk）の変更。
tenant_id、lob_idでpkとする。
（r_idを用意する必要がない）
また、obj_blob_rbテーブルも同様に、tenant_id、rb_idでpkとする。

**Comment by xsuzukiyosuke** [comment]
_(English)_
Change index (pk) of obj_blob table at mysql (aurora).
Let tenant_id and lob_id be pk.
(No need to prepare r_id)
Similarly, the obj_blob_rb table is also pk with tenant_id and rb_id.
