### ISSUE TITLE
gem、UserPropertyEditorでユーザ名解決する際、検索処理の特権実行有無を設定可能にする

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#838]
gemにおいてUserPropertyEditorでユーザ名解決する際、ユーザ情報取得処理の特権実行有無を設定可能にする

**Comment by xminagawa** [comment]
_(English)_
Enable to configure whether the user information acquisition process is privileged or not when resolving user names with UserPropertyEditor in gem.
