### ISSUE TITLE
ファイルアップロード時のマジックバイトチェックの改善

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#851]
ファイルアップロード時のマジックバイトチェックの改善。
office形式の判定の改善。
MSOffice以外で作成されたOOXML形式も対象とできるように。

**Comment by xsuzukiyosuke** [comment]
_(English)_
Improve magic byte check when uploading files.
Improve office style judgment.
Make it possible to target OOXML formats created outside of MS Office.
