### ISSUE TITLE
画面定義で設定可能な項目が表示されない

### ISSUE THREAD

**Issue by yoshiharuyasuda** [ISID/iPLAss#86]
3.0.3から画面定義で幾つかの項目が表示されず、設定が出来なくなってる。

以下は確認できた部分。
・DetailFormのボタンの「新規登録/編集時の編集可否」や「表示タイプ」
・NestPropertyの項目（ReferencePropertyEditorから設定した時と、MassReferenceSectionから設定した時で表示される項目が違う）

**Comment by houshiPLAss** [comment]
EntityViewFieldアノテーションを利用しないフィールドの場合、nullでトリガータイプを上書きしまったので、利用しない場合、上書きをしないように修正する。
