### ISSUE TITLE
GEMのCSVアップロードで更新可能項目の制限を可能に

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#864]
GEMのCSVアップロードで更新可能項目の制限を可能にする。
EntityView定義にて、CSVでの更新可否（登録、更新、削除それぞれ）フラグ、および登録更新可能プロパティの指定を可能にする。

**Comment by xsuzukiyosuke** [comment]
_(English)_
Enable to limit updatable properties at CSV upload of GEM.
In the EntityView definition, it is possible to specify the update enable/disable flag (insert, update, and delete) in CSV, and the updateable properties.
