### ISSUE TITLE
gem、検索の際にReference項目にEntity権限の限定条件を付与するか否かを設定可能にする

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#874]
gem、検索の際にReference項目にEntity権限の限定条件を付与するか否かを設定可能にする。
メインEntityへの限定条件が付与されることにより、Reference項目のセキュリティ的な限定条件も充足する場合、Reference項目に冗長な限定条件が付与されることを回避するためのフラグ。

設定されたReferenceを
SearchQueryContext.withoutConditionReferenceName
にセットし、最終的には以下を呼び出すことで実現。
EntityPermission#doQueryAs(String[] withoutConditionReferenceName, Supplier<T> action)

**Comment by xminagawa** [comment]
_(English)_
Allows the gem to set whether or not to grant Entity authority limitation conditions to Reference items when searching.
Flag to avoid redundant limitation conditions on Reference items when the security limitation conditions of Reference items are also satisfied by granting the limitation conditions to the main Entity.

The set Reference is then stored in the
"SearchQueryContext.withoutConditionReferenceName"
and finally by calling
EntityPermission#doQueryAs(String[] withoutConditionReferenceName, Supplier action)
