### ISSUE TITLE
gem、ヘッダー部に表示するテナント名をGroovyTemplateとして処理し動的に出力可能に

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#878]
gem、ヘッダー部に表示するテナント名をGroovyTemplateとして処理し動的に出力可能に。
※htmlのheadタグのtitleおよび、画面表示上のヘッダー部のテナント名に対応が必要。

**Comment by xsuzukiyosuke** [comment]
_(English)_
The tenant name displayed in the header part at gem is processed as GroovyTemplate and can be output dynamically.
※It is necessary to correspond to the title of the head tag of html and the tenant name of the header part on the screen display.
