### ISSUE TITLE
MySQLでdecimal型、DIV関数を利用する場合の注意書きをadminConosleでのDecimalPropperty設定時に注意喚起する

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#881]
MySQLでdecimal型、DIV関数を利用する場合の注意書きをadminConosleでのDecimalPropperty設定時に注意喚起する。
システム変数のdiv_precision_incrementを適切に設定が必要。
Decimal型の場合は小数点以下桁数の最大桁数の設定が必要。

**Comment by xminagawa** [comment]
_(English)_
A reminder to use the decimal type and DIV function in MySQL when setting DecimalProperty in adminConosle.
The system variable DIV_PRECISION_INCREMENT must be set appropriately.
In case of Decimal type, the maximum number of decimal places should be set.
