### ISSUE TITLE
gemの自動補完機能、ラベル形式であっても補完可能に

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#886]
gemの自動補完機能、ラベル形式であっても補完可能に。
ラベル形式、HIDDEN形式、仮想プロパティ項目であっても設定により補完可能にする。

**Comment by xminagawa** [comment]
_(English)_
gem auto-completion function, even label format can be completed.
Enable completion of label format, HIDDEN format, and virtual property items by setting.
