### ISSUE TITLE
EntityのEventListener定義でSendNotificationタイプのレイアウトを調整

### ISSUE THREAD

**Issue by houshiPLAss** [ISID/iPLAss#89]
・EntityのEventListener定義でScriptタイプのレイアウトに合わせて、SendNotificationタイプのイベント種別設定フォームを一つ上に移動

**Comment by HiguchiKiyoshi** [comment]
#32 の追加の修正なので、Milestone3.0.4からは外しとく（周知が必要なIssueとしない）
