### ISSUE TITLE
AdminConsole、gemの日付系PropertyEditorの「日付/時刻のフォーマットの多言語設定」の英語タイトルが不正

### ISSUE THREAD

**Issue by xkazama-yukio3** [ISID/iPLAss#937]
gemのEntityView編集画面にて、日付系PropertyEditorの「日付/時刻のフォーマットの多言語設定」の英語タイトルが日本語で表示されている。

**Comment by xminagawa** [comment]
(_English_)
On gem's EntityView edit screen, the English title of "Multilingual settings for date/time format" in the date-based PropertyEditor is displayed in Japanese.
