### ISSUE TITLE
mysql（aurora）のobj_blob_rbテーブルのindex（pk）の変更

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#938]
mysql（aurora）のobj_blob_rbテーブルのindex（pk）の変更
#831 でpkを変更したが、obj_blob_rbテーブルのpk指定が正しくない。
正しくはtenant_id、lob_idがpkで、従来通りtenant_id、rb_idはindex（非ユニーク）

**Comment by xsuzukiyosuke** [comment]
_(English)_
Change index (pk) of obj_blob table at mysql (aurora).
It changed the pk in #831, but the pk specification in the obj_blob_rb table is incorrect.
Correctly, tenant_id and lob_id are pk, and tenant_id and rb_id are index (non-unique) as before
