### ISSUE TITLE
gem、ReferencePropertyEditorの表示ラベルにoidを指定すると正常に動作しない

### ISSUE THREAD

**Issue by xkazama-yukio3** [ISID/iPLAss#980]
ReferencePropertyEditorの表示ラベルに `oid` を指定すると、正しく紐づけされない状態になる。
表示ラベルとしては `oid` が表示されるが、内部で保持する値が `undefined` となってしまう。

**Comment by xminagawa** [comment]
_(English)_
When  `oid`  is specified as the display label in ReferencePropertyEditor, it is not tied correctly.
Although  `oid`  is displayed as the display label, the internally held value is  `undefined` .
