### ISSUE TITLE
GEM、お知らせ詳細画面でTopView定義がロールと連動していない

### ISSUE THREAD

**Issue by yumaishida** [ISID/iPLAss#995]
GEM、お知らせ詳細画面でTopView定義がロールと連動していない。
詳細画面では `DEFAULT`のTopView定義を見てしまっている。

**Comment by xkazama-yukio3** [comment]
_(English)_
The TopView definition that matches the selected role is not referenced on the information details screen.
The information detail screen refers to the `DEFAULT` TopView definition.
