### ISSUE TITLE
CORSの許可するドメイン設定でサブドメインの許可を簡易に設定できるようにする

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [ISID/iPLAss#998]
CORSの許可するドメイン設定でサブドメインの許可を簡易に設定できるようにする。
*.isid.co.jp
のようにサブドメインにワイルドカードを指定可能に。
WebAPI定義および、WebFrontendServiceの設定にて。

**Comment by xsuzukiyosuke** [comment]
_(English)_
Make it easy to set subdomain permissions in CORS allowed domain settings.
*.isid.co.jp
Wildcards can be specified for subdomains like this.
In the WebAPI definition and WebFrontendService settings.
